### PR TITLE
Fix possible crash or deadlock arising from calling notify() from multiple queues concurrently

### LINKED ISSUE #399: SIGABRT in notifyError
### Issue
We're seeing a SIGABRT inside of Bugsnag in the call to `notifyError:…`.

Here's the trace:
```
SIGABRT: 

0  libsystem_kernel.dylib  ___pthread_kill
1  libsystem_pthread.dylib _pthread_kill
2  libsystem_c.dylib       _abort
3  libsystem_malloc.dylib  _malloc_vreport
4  libsystem_malloc.dylib  _malloc_report
5  libsystem_malloc.dylib  _free
6  PlanGrid                bsg_ksstring_replace (BSG_KSString.c:143:9)
7  PlanGrid                bsg_kscrash_reinstall (BSG_KSCrashC.c:194:5)
8  PlanGrid                -[BSG_KSCrash reportUserException:reason:originalException:handledState:appState:callbackOverrides:metadata:config:discardDepth:terminateProgram:] (BSG_KSCrash.m:324:5)
9  PlanGrid                -[BugsnagCrashSentry reportUserException:reason:originalException:handledState:appState:callbackOverrides:metadata:config:discardDepth:] (BugsnagCrashSentry.m:53:5)
10 PlanGrid                -[BugsnagNotifier notify:handledState:block:] (BugsnagNotifier.m:665:5)
11 PlanGrid                -[BugsnagNotifier notifyError:block:] (BugsnagNotifier.m:530:5)
```

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere): 5.22.4
* CocoaPods version (if any) (`pod -v`): 1.7.2
* Carthage version (if any):
* iOS/tvOS/macOS version(s) iOS 11+
* debug mode or production?: Production
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

### Example code snippet

```swift
import Bugsnag
// title is a String
// message is a String
// severity is an enum, which we map to a Bugsnag severity
        let bugsnagError = NSError(domain: "com.loupe.PlanGrid", code: 0, userInfo: [
            NSLocalizedDescriptionKey: title,
            NSLocalizedFailureReasonErrorKey: message
        ])

        Bugsnag.notifyError(bugsnagError) { report in
            report.errorClass = title
            report.errorMessage = message
            report.severity = severity.bugsnagSeverity
            additionalData?.forEach { key, value in
                report.metaData[key] = value
            }
            report.context = "ErrorLogger.logError"
        }
```

Here's the ID of the error in the plangrid iOS Bugsnag project :) 5c86619cc74b1f0019fc8ecc. Feel free to go have a look!

### PR DESCRIPTION
**Pull request by kattrali**
## Goal

Its possible that when `notify()` is called concurrently from multiple queues, that a crash occurs when caching/resetting crash state. This changeset solves the underlying issues by not sharing state between calls to `notify()` and isolating calls to suspend threads (for backtrace collection).

### Reproduction case

```objc
dispatch_queue_t queue1 = dispatch_queue_create("Queue 1", DISPATCH_QUEUE_CONCURRENT);
dispatch_queue_t queue2 = dispatch_queue_create("Queue 2", DISPATCH_QUEUE_CONCURRENT);

for (int i = 0; i < 4; i++) {
    NSString *message = [NSString stringWithFormat:@"Err %ld", (long)i];
    NSError *error = [FooError errorWithDomain:@"com.example"
                                          code:340
                                      userInfo:nil];
    dispatch_async(queue1, ^{
        [Bugsnag notifyError:error];
    });
    dispatch_async(queue2, ^{
        [Bugsnag notifyError:error];
    });
}
```

Fixes #399

## Changeset

The changes can be divided into four parts:

1. Adding a (failing on master) test which calls `notify()` several times from different concurrent queues
2. Refactoring crash reporting internals to allow providing separate crash contexts for each invocation of `notify()`
3. Implementing separate crash contexts for `notify()` calls
4. Adding locking around suspending threads and writing crash state.

The easiest way to view the changeset is one commit at a time, since each chunk can be evaluated independently.

## Tests

* Tested manually on a couple different iOS/tvOS devices running iOS 11 & 12
* Added automated tests replicating the failing scenario

### CODE REVIEW

File: Tests/KSCrash/KSCrashIdentifierTests.m [hunk 1]
```diff
@@ -0,0 +1,32 @@
+#import <XCTest/XCTest.h>
+#import <string.h>
+#import "BSG_KSCrashIdentifier.h"
+
+@interface KSCrashIdentifierTests : XCTestCase
+@end
+
+@implementation KSCrashIdentifierTests
```
Comment (tomlongridge) [inline Tests/KSCrash/KSCrashIdentifierTests.m]: Can we include a test for `bsg_kscrash_generate_report_path`?

**Comment by nkavian** [comment]
When will a new release be ready? Thanks.

File: Tests/KSCrash/KSCrashIdentifierTests.m (hunk 1 above)
Comment (kattrali) [reply Tests/KSCrash/KSCrashIdentifierTests.m]: Yeah I should - it turned out to be a bit tricky to stub the file store but I've added a task to improve coverage here.

**Comment by kattrali** [comment]
Hi @nkavian! Doing a release now, should be available soon.

**Comment by nkavian** [comment]
Thanks, confirming the latest release fixed my issue!
