### PR TITLE
Send severity and breadcrumbs with uncaught exceptions

### LINKED ISSUE #58: Missing Severity
The severity is not being sent in some situations

### PR DESCRIPTION
**Pull request by kattrali**
## Changes

* Set and serialize default severity as `error` in case of an uncaught exception. It is still overridden in the case of a handled exception.
* Serialize breadcrumbs after each change
* Refactor `serializedDictionary:toJSON:` into a function, `BSSerializeJSONDictionary`
* Rename onCrash handler to indicate purpose

Fixes #58

### CODE REVIEW

File: Source/Bugsnag/BugsnagNotifier.m [hunk 1]
```diff
@@ -114,27 +148,29 @@ - (void)notify:(NSException *)exception withData:(NSDictionary *)metaData atSeve
...
     [self.metaDataLock unlock];
     [self metaDataChanged: self.configuration.metaData];
-    [[self state] clearTab:@"crash"];
+    [[self state] clearTab:BSTabCrash];
 
     [self performSelectorInBackground:@selector(sendPendingReports) withObject:nil];
+    [self resetDefaultSeverity];
+}
+
+- (void) resetDefaultSeverity {
```
Comment (snmaynard) [inline Source/Bugsnag/BugsnagNotifier.m]: Could we instead say that if severity is nil then we should set it to error in the sink?

**Comment by snmaynard** [comment]
This LGTM!

File: Source/Bugsnag/BugsnagNotifier.m (hunk 1 above)
Comment (kattrali) [inline Source/Bugsnag/BugsnagNotifier.m]: I wondered about that. Is it weird to modify the payloads during the filter step though?

Comment (snmaynard) [inline Source/Bugsnag/BugsnagNotifier.m]: I dont think so. I think we'd just be saying that if one wasnt written it was in fact an error. I dont mind which direction we head in but wanted to point it out as an option.

Comment (kattrali) [inline Source/Bugsnag/BugsnagNotifier.m]: Yeah, I could see that. and then I can move all of this logic as one unit. Patched.

**Comment by snmaynard** [comment]
:+1: :+1: :deciduous_tree:
