### PR TITLE
fix(breadcrumbs): guard read access to breadcrumbs count

### LINKED ISSUE #199: Are breadcrumbs not thread-safe?
https://app.bugsnag.com/recharge-labs/ios/errors/59f2781c96d78c00199afa65

### Expected behavior
non-fatal error is logged to the server, even if somebody tries to add a breadcrumb while we're in the middle of a `notifyError` call.

### Observed behavior
SIGABRT
https://app.bugsnag.com/recharge-labs/ios/errors/59f2781c96d78c00199afa65
The top level stacktrace just has one useful line #: `AppDelegate.swift:226` which is a call to `Bugsnag.leaveBreadcrumb(withMessage: logMessage.message)`
In the "threads" view, thread 19 is in the middle of doing a `Bugsnag.notifyError`

### Steps to reproduce
Unclear.  I have not been able to repro this myself.  But I imagine if you made an infinite loop that just called `leaveBreadcrumb` and then occasionally fired off calls to `notifyError`, you'd eventually trigger it.

### Version
5.13.0

### Additional information
I made the change to run notifyError from a background thread in a version of our app that went live on 10/15, and it just today (10/26) triggered this error, so I'm guessing it's a pretty rare race condition-y situation.

### LINKED ISSUE #616: Breadcrumb API is not thread-safe
### Description

While running our app under the thread sanitiser, it frequently hits a race condition on the Breadcrumb API as seen here:

Screenshot 2020-05-22 at 11 09 20
Screenshot 2020-05-22 at 11 09 41

### Environment

Library versions:

* Bugsnag version (from your Podfile, Podfile.lock, or elsewhere):
* CocoaPods version (if any) (`pod -v`):
* Carthage version (if any):
* iOS/tvOS/macOS version(s)
* debug mode or production?:
* How are you initializing Bugsnag? Can you share a snippet of your
  `AppDelegate` where Bugsnag is configured?

### Example code snippet

```swift
import Bugsnag

// (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

### PR DESCRIPTION
**Pull request by tomlongridge**
## Goal

Fixes #616 

## Design

Refactored access to breadcrumb list to avoid the need for the `readWriteQueue` guard in most cases.

## Changeset

* BugsnagBreadcrumbs - removed `capacity`, `count`, and `objectAtIndexedSubscript` as no longer needed
* BugsnagBreadcrumbs:arrayValue - removed `readWriteQueue` guard and used a copy of the list instead; also made signature nonnull to return empty array if there are no elements.
* BugsnagConfiguration / BugsnagClient - moved the `breadcrumbs` field from configuration to client and added fields to configuration for `maxBreadcrumbs` and `enabledBreadcrumbTypes`. These are then used in the `BugsnagBreadcrumbs` constructor. This prevents any need for resizing the array of breadcrumbs outside the class.

## Tests

* Enabled Thread Sanitizer and added breadcrumbs in a tight loop to check for issues.
* Amended unit tests accordingly

### CODE REVIEW

**Comment by tomlongridge** [comment]
I've removed internal access to the `count` property. Now we have a clearer distinction between internal and external headers, can we remove it?

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m [hunk 1]
```diff
@@ -137,52 +137,56 @@ - (void)setCapacity:(NSUInteger)capacity {
...
 - (NSUInteger)count {
-    return self.breadcrumbs.count;
+    __block NSUInteger count;
+    dispatch_barrier_sync(self.readWriteQueue, ^{
+        count = self.breadcrumbs.count;
+    });
+    return count;
 }
 
 - (BugsnagBreadcrumb *)objectAtIndexedSubscript:(NSUInteger)index {
```
Comment (fractalwrench) [inline Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:147]: This method appears to be unused so can be removed

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m [hunk 2]
```diff
@@ -137,52 +137,56 @@ - (void)setCapacity:(NSUInteger)capacity {
...
-                              @"JSON object");
-                  continue;
-              }
-              [contents addObject:objectValue];
-          } @catch (NSException *exception) {
-              bsg_log_err(@"Unable to serialize breadcrumb: %@", error);
-          }
-      }
+        NSUInteger numBreadcrumbs = self.breadcrumbs.count;
+        if (numBreadcrumbs > 0) {
```
Comment (fractalwrench) [inline Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:161]: nit: removing this check would mean that the method never needs to return `nil` and could be annotated as nonnull - which feels a better behaviour for an empty collection.

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m [hunk 3]
```diff
@@ -137,52 +137,56 @@ - (void)setCapacity:(NSUInteger)capacity {
...
 }
 
 - (NSArray *)arrayValue {
-    if ([self count] == 0) {
-        return nil;
-    }
-    __block NSMutableArray *contents =
-        [[NSMutableArray alloc] initWithCapacity:[self count]];
+    __block NSMutableArray *contents = nil;
     dispatch_barrier_sync(self.readWriteQueue, ^{
```
Comment (fractalwrench) [inline Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:159]: I'm not convinced that a dispatch barrier is necessary - being defensive and serializing a `mutableCopy` of `self.breadcrumbs` should be sufficient IMO.

**Comment by tomlongridge** [comment]
> This touches more on the overall class design, but it's worth noting that using `dispatch_barrier_sync` for a method that can be called from the main thread is not great. This is because it will block until IO completes.
> 
> Fortunately I think it should be possible to replace this with `dispatch_barrier_async` because the only remaining method after implementing these suggestions would be `cachedBreadcrumbs`. This is always called before breadcrumb collection happens, so could be extracted out to `BugsnagClient/BSGOutOfMemoryWatchdog`. This is potentially a bit out of the scope of this changeset so it'd be acceptable to address this when the breadcrumb disk serialization is revisited in general.

I haven't addressed this as there are wider issues trying to run this asynchronously. I'll raise this separately for a future change as this should be a good efficiency gain.

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m [hunk 4]
```diff
@@ -59,14 +55,16 @@ - (void)addBreadcrumb:(NSString *)breadcrumbMessage {
...
-    if (self.capacity == 0) {
+    if (self.config.maxBreadcrumbs == 0) {
         return;
     }
     BugsnagBreadcrumb *crumb = [BugsnagBreadcrumb breadcrumbWithBlock:block];
 
     if (crumb != nil && [self shouldSendBreadcrumb:crumb]) {
-        [self resizeToFitCapacity:self.capacity - 1];
         dispatch_barrier_sync(self.readWriteQueue, ^{
+            while ([self.breadcrumbs count] >= self.config.maxBreadcrumbs) {
```
Comment (fractalwrench) [inline Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:65]: This will crash if `maxBreadcrumbs == 0`

File: Bugsnag/Configuration/BugsnagConfiguration.m [hunk 5]
```diff
@@ -455,16 +450,23 @@ -(void)deletePersistedUserData {
 // MARK: - Properties: Getters and Setters
 // -----------------------------------------------------------------------------
 
+@synthesize maxBreadcrumbs = _maxBreadcrumbs;
+
 - (NSUInteger)maxBreadcrumbs {
-    return self.breadcrumbs.capacity;
+    @synchronized (self) {
```
Comment (fractalwrench) [inline Bugsnag/Configuration/BugsnagConfiguration.m:456]: I don't see why this needs to take out a lock - I'm aware this is done elsewhere for other properties but think this could be removed for the majority if not all of those custom accessors, unless there's a specific reason. Possibly something to raise in another ticket.

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m (hunk 4 above)
Comment (tomlongridge) [reply Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:65]: This is excluded above (L58).

File: Bugsnag/Configuration/BugsnagConfiguration.m (hunk 5 above)
Comment (tomlongridge) [reply Bugsnag/Configuration/BugsnagConfiguration.m:456]: I'd rather stick with the pattern used already - will raise a ticket to consider this in future.

File: Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m (hunk 4 above)
Comment (tomlongridge) [reply Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m]: In fact, it makes me nervous in case the count is zero, so I've removed the loop (it will never be more than the max) and added a check for count>0.

**Comment by tomlongridge** [comment]
This PR also fixes #737

**Comment by raylillywhite** [comment]
I'm using commit 9044a26a6f3e8909209b598d6ecc12d4d20adb23 and still getting crashes

```
EXC_BAD_ACCESS · Attempted to dereference garbage pointer 0xd590dd120.
/usr/lib/libobjc.A.dylib_objc_msgSend	
Bugsnag/Bugsnag/Breadcrumbs/BugsnagBreadcrumbs.m:122:37-[BugsnagBreadcrumbs arrayValue]	
Bugsnag/Bugsnag/Client/BugsnagClient.m:1096:29-[BugsnagClient serializeBreadcrumbs]	
Bugsnag/Bugsnag/Client/BugsnagClient.m:781:5-[BugsnagClient leaveBreadcrumbWithMessage:metadata:andType:]	
Bugsnag/Bugsnag/Bugsnag.m:187:9+[Bugsnag leaveBreadcrumbWithMessage:metadata:andType:]
```

Link [here](https://app.bugsnag.com/spruce-health/care-messenger-ios/errors/5f075415a85fb200171927ab?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=staging&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=5f07fe58005b8c49c1270000) in case you have access to all bugsnag data

**Comment by tomlongridge** [comment]
Thanks @raylillywhite - I'm investigating now.

**Comment by tomlongridge** [comment]
@raylillywhite - I haven't been able to reproduce this, but it does seem that we're somehow holding on to a freed reference, even though the mutable copy should have preserved the reference.

Are you able to readily reproduce this in a non-live environment? I have pushed a change (808b8bce8d0c99e2c16a2c2f89ae0a8129b38fa8) that reinstates the barrier guard for `arrayValue` so that the operation is protected as it was before #743. I was wondering if you'd be able to see if this resolves the issue for you?

**Comment by raylillywhite** [comment]
I can't reproduce it on demand, but we saw it quite a few times (we log a lot of breadcrumbs). And we're not shipping for a few weeks so I'll use that commit in our next test build today and see if it still happens.
